# Cấu hình kết nối tới TiDB Cloud (Serverless)
# Bạn thay <PASSWORD> bằng mật khẩu bạn đã tạo trong bước "Generate Password" trên TiDB Cloud
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/ielts_db?useSSL=true&enabledTLSProtocols=TLSv1.2&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=4PDCe8n7xxf2A6A.root
spring.datasource.password=go7Uu6KxBBP8bwko
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình JPA cho TiDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect